### ISSUE TITLE
Repository Basics

### ISSUE THREAD

**Issue by ElectronicsArchiver** [animerl/novelai-2-local-prompt#1]
I would like to suggest you to:

- Disable unused features such as

  - Actions
  - Projects
  - Releases
  - Packages

- Add a license
  
  https://choosealicense.com/

- Add the following tags
 
  - `tool`
  - `script`

**Comment by animerl** [comment]
> I would like to suggest you to:
> 
>     * Disable unused features such as
>       
>       * Actions
>       * Projects
>       * Releases
>       * Packages
> 
>     * Add a license
>       https://choosealicense.com/
> 
>     * Add the following tags
>       
>       * `tool`
>       * `script`

Thank you. I carried out.
