### ISSUE TITLE
[Request] Add more simple description

### ISSUE THREAD

**Issue by krisfail** [animerl/novelai-2-local-prompt#3]
sample:
NovelAIで使われるプロンプトを、WebUIで使えるように変換するボタンを追加します。
加えて、前に使ったプロンプトを呼び戻すことができるボタンも追加します。

Add a button to convert the prompts used in NovelAI for use in the WebUI.
In addition, add a button that allows you to recall a previously used prompt.

**Comment by animerl** [comment]
thx
