### ISSUE TITLE
May I ask that how it handles prompt like (())

### ISSUE THREAD

**Issue by aetherwu** [animerl/novelai-2-local-prompt#9]
Like this one:

((masterpiece)), best quality, (((extremely detailed CG))), ((ultra-detailed)), ((highres)), ((extremely_detailed_eyes_and_face))

It turns to 

`\(\(masterpiece\)\), best quality, \(\(\(extremely detailed CG\)\)\), \(\(ultra-detailed\)\), \(\(highres\)\), \(\(extremely_detailed_eyes_and_face\)\)`

Is that correct?

**Comment by animerl** [comment]
Probably correct (I don't know because I do not currently have an NAI subscription.)
In any case, it is an invalid prompt and therefore need not be considered.
